# Standard things
sp := $(sp).x
dirstack_$(sp) := $(d)
d	:= $(dir)

# Vars
TEST_DOCKER_BATS_DIR := $(d)
TEST_DOCKER_BATS_ABS_DIR := $(MKFILE_DIR)/$(d)
TEST_DOCKER_BATS_GNU_LIST := true
TEST_DOCKER_BATS_VERSION := 4c98d3ad65eb77e5caf56984cdc67674e656e980
TEST_DOCKER_BATS_IMAGE_NAME ?= fzf-obc-test
TEST_DOCKER_BATS_IMAGE_FULL_NAME ?= $(TEST_DOCKER_REGISTRY)$(TEST_DOCKER_REGISTRY_NAMESPACE)$(TEST_DOCKER_BATS_IMAGE_NAME)
TEST_DOCKER_BATS_DOCKERFILES_LIST := $(notdir $(basename $(wildcard $(d)/*.dockerfile)))
TEST_DOCKER_BATS_IMAGES_TARGET_PREFIX := test-docker-bats-build
TEST_DOCKER_BATS_IMAGES_LIST := $(foreach gnu,$(TEST_DOCKER_BATS_GNU_LIST),$(addsuffix -gnu-$(gnu),$(TEST_DOCKER_BATS_DOCKERFILES_LIST)))
TEST_DOCKER_BATS_IMAGES_TARGETS := $(addprefix $(TEST_DOCKER_BATS_IMAGES_TARGET_PREFIX)-,$(TEST_DOCKER_BATS_IMAGES_LIST))
TEST_DOCKER_BATS_PUBLISH_TARGET_PREFIX := test-docker-bats-publish
TEST_DOCKER_BATS_PUBLISH_TARGETS := $(addprefix $(TEST_DOCKER_BATS_PUBLISH_TARGET_PREFIX)-,$(TEST_DOCKER_BATS_IMAGES_LIST))
TEST_DOCKER_BATS_DOWNLOAD_TARGET_PREFIX := test-docker-bats-download
TEST_DOCKER_BATS_DOWNLOAD_TARGETS := $(addprefix $(TEST_DOCKER_BATS_DOWNLOAD_TARGET_PREFIX)-,$(TEST_DOCKER_BATS_IMAGES_LIST))

#####
# Targets
#####

# Download
.PHONY: $(TEST_DOCKER_BATS_DOWNLOAD_TARGETS)
$(TEST_DOCKER_BATS_DOWNLOAD_TARGETS): $(TEST_DOCKER_BATS_DOWNLOAD_TARGET_PREFIX)-% :
	$(info ##### Downloading '$(TEST_DOCKER_BATS_IMAGE_NAME):$(*)' docker image #####)
	docker pull \
		--quiet \
		$(TEST_DOCKER_BATS_IMAGE_FULL_NAME):$(*) || true

# Build
.PHONY: $(TEST_DOCKER_BATS_IMAGES_TARGET_PREFIX)
$(TEST_DOCKER_BATS_IMAGES_TARGET_PREFIX): $(TEST_DOCKER_BATS_IMAGES_TARGETS)

.PHONY: $(TEST_DOCKER_BATS_IMAGES_TARGETS)
$(TEST_DOCKER_BATS_IMAGES_TARGETS): $(TEST_DOCKER_BATS_IMAGES_TARGET_PREFIX)-% : $(TEST_DOCKER_BATS_DOWNLOAD_TARGET_PREFIX)-%
	$(info ##### Updating '$(TEST_DOCKER_BATS_IMAGE_NAME):$(*)' docker image #####)
	docker build \
		--quiet \
		-f $(TEST_DOCKER_BATS_DIR)/$(subst -gnu-,,$(strip $(foreach dockerfile,$(TEST_DOCKER_BATS_DOCKERFILES_LIST),$(findstring $(dockerfile)-gnu-,$(*))))).dockerfile \
		--build-arg GNU="$(subst -gnu-,,$(strip $(foreach gnu,$(TEST_DOCKER_BATS_GNU_LIST),$(findstring -gnu-$(gnu),$*))))" \
		--build-arg BATS_VERSION="$(TEST_DOCKER_BATS_VERSION)" \
		--build-arg BASH_VERSION="$(subst bash-,,$(strip $(foreach bash,$(TEST_DOCKER_BATS_DOCKERFILES_LIST),$(findstring $(bash),$*))))" \
		-t $(TEST_DOCKER_BATS_IMAGE_NAME):$(subst $(TEST_DOCKER_BATS_IMAGES_TARGET_PREFIX)-,,$@) \
		$(TEST_DOCKER_BATS_DIR)

# Publish
.PHONY: $(TEST_DOCKER_BATS_PUBLISH_TARGET_PREFIX)
$(TEST_DOCKER_BATS_PUBLISH_TARGET_PREFIX): $(TEST_DOCKER_BATS_PUBLISH_TARGETS)

.PHONY: $(TEST_DOCKER_BATS_PUBLISH_TARGETS)
$(TEST_DOCKER_BATS_PUBLISH_TARGETS): $(TEST_DOCKER_BATS_PUBLISH_TARGET_PREFIX)-% :  test-docker-login $(TEST_DOCKER_BATS_IMAGES_TARGET_PREFIX)-%
	$(info ##### Publishing '$(TEST_DOCKER_BATS_IMAGE_NAME):$(*)' on registry $(TEST_DOCKER_REGISTRY) #####)
	docker image tag $(TEST_DOCKER_BATS_IMAGE_NAME):$* $(TEST_DOCKER_BATS_IMAGE_FULL_NAME):$*
	docker push $(TEST_DOCKER_BATS_IMAGE_FULL_NAME):$*


# Standard things
d := $(dirstack_$(sp))
sp := $(basename $(sp))
