---
sudo: required
language: ruby
dist: bionic
services:
  - docker
addons:
  apt:
    sources:
      - sourceline: "ppa:kimura-o/ppa-tmux"
      - sourceline: "deb https://download.docker.com/linux/ubuntu bionic stable"
        key_url: "https://download.docker.com/linux/ubuntu/gpg"
    update: true
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - tmux
      - python3
stages:
  - name: tests
  - name: mkrelease
    if: |
      branch = master \
      AND type != pull_request
jobs:
  include:
    - stage: tests
      script:
        - make test

    - stage: mkrelease
      install:
        - wget --quiet -O /tmp/mkrelease.sh https://raw.githubusercontent.com/rockandska/scripts/${MKRELEASE_REF:-master}/CI/mkrelease.sh
        - chmod +x /tmp/mkrelease.sh
        - wget --quiet -O /tmp/pubrelease.sh https://raw.githubusercontent.com/rockandska/scripts/${PUBRELEASE_REF:-master}/CI/pubrelease.sh
        - chmod +x /tmp/pubrelease.sh
      script:
        - TRAVIS_TAG=$(/tmp/mkrelease.sh || travis_terminate 1)
        - export TRAVIS_TAG
      deploy:
        provider: script
        script: /tmp/pubrelease.sh
        skip_cleanup: true
        on:
          tags: true
