site_name: FZF-OBC
site_url: https://fzf-obc.readthedocs.io
site_description: Fzf over bash complete
site_author: RockAndSka

repo_url: https://github.com/rockandska/fzf-obc/

nav:
  - index.md
  - prerequisites.md
  - installation.md
  - triggers_type.md
  - user_config.md
  - plugins.md
  - plugins_list.md
  - About:
      - Changelog: changelog.md
      - Demo Gallery: tests_gallery.md
      - How fzf-obc works: how_it_works.md

theme:
    name: readthedocs
    highlightjs: true
    custom_dir: docs/custom_theme

plugins:
    - search
