#!/usr/bin/env bash
_filedir_xspec()
{
  local cur="${cur}"
  __fzf_obc_tilde "${cur%%\**}" || return
  local xspec
  # shellcheck disable=SC2154
  xspec="${_xspecs[${1##*/}]}"
  local matchop=!;
  if [[ $xspec == !* ]]; then
      xspec=${xspec#!};
      matchop=@;
  fi;
  [[ ${BASH_VERSINFO[0]} -ge 4 ]] && xspec="$matchop($xspec|${xspec^^})" || xspec="$matchop($xspec|$(printf %s "$xspec" | tr '[:lower:]' '[:upper:]'))";
  __fzf_add2compreply < <(__fzf_obc_search "${cur}" "paths" "${xspec}")

  if [[ "${#COMPREPLY[@]}" -gt 0 ]];then
    type compopt >&/dev/null && compopt -o filenames 2> /dev/null || compgen -f /non-existing-dir/ > /dev/null
  fi

  return 0
}
