#!/usr/bin/env bash
_filedir_xspec()
{
  local cur="${cur}"
  __fzf_obc_tilde "${cur%%\**}" || return
  local xspec
  # shellcheck disable=SC2154
  xspec="${_xspecs[${1##*/}]}"
  local matchop=!;
  if [[ $xspec == !* ]]; then
      xspec=${xspec#!};
      matchop=@;
  fi;
  if [[ ${BASH_VERSINFO[0]} -ge 4 ]];then
    xspec="$matchop($xspec|${xspec^^})"
  else
    if [[ -z "${xspec}" ]];then
      xspec=$( awk "/^complete[ \t]+.*[ \t]${1##*/}([ \t]|\$)/ { print \$0; exit }"         "$BASH_COMPLETION" );
      xspec=${xspec#*-X };
      xspec=${xspec%% *};
      xspec="$matchop($xspec|$(printf %s "$xspec" | tr '[:lower:]' '[:upper:]'))"
    fi
  fi

  __fzf_add2compreply < <(__fzf_obc_search "${cur}" "paths" "${xspec}")

  if [[ "${#COMPREPLY[@]}" -gt 0 ]];then
    if type compopt >&/dev/null ;then
      compopt -o filenames 2> /dev/null
    else
      compgen -f /non-existing-dir/ > /dev/null
    fi
  fi

  return 0
}
