#!/usr/bin/env bash
_filedir_xspec()
{
  __fzf_obc_tilde "${cur%%\**}" || return
  local xspec
  # shellcheck disable=SC2154
  xspec="${_xspecs[${1##*/}]}"
  local matchop=!;
  if [[ $xspec == !* ]]; then
      xspec=${xspec#!};
      matchop=@;
  fi;
  xspec="$matchop($xspec|${xspec^^})";
  __fzf_add2compreply < <(__fzf_obc_search "${cur}" "paths" "${xspec}")

  if [[ "${#COMPREPLY[@]}" -gt 0 ]];then
    compopt -o filenames
  fi

  return 0
}
