#!/usr/bin/env bash


__fzf_add2compreply() {
  # Input: string separated by $'\0'
  if ! readarray -d $'\0' -O "${#COMPREPLY[@]}" COMPREPLY 2> /dev/null;then
    while IFS=$'\0' read -r -d '' line;do COMPREPLY+=( "${line}" );done
  fi
}

__fzf_compreply() {
  # Input: string separated by $'\0'
  if ! readarray -d $'\0' COMPREPLY 2> /dev/null;then
    IFS=$'\0' read -r -d '' -a COMPREPLY
  fi
}
__fzf_obc_sort_cmd() {
  # sort cmd used to show results
  (LC_ALL=C sort -ufrz -S 50% --parallel="$( awk '/^processor/{print $3}' < /proc/cpuinfo | wc -l)" 2> /dev/null || LC_ALL=C sort -ufrz)
}

# get find exclude pattern
__fzf_obc_globs_exclude() {
  local var=$1
  local sep str fzf_obc_globs_exclude_array
  IFS=':' read -r -a fzf_obc_globs_exclude_array <<< "${FZF_OBC_EXCLUDE_PATH}"
  if [[ ${#fzf_obc_globs_exclude_array[@]} -ne 0 ]];then
    str="\( -path '*/${fzf_obc_globs_exclude_array[0]%/}"
    for pattern in "${fzf_obc_globs_exclude_array[@]:1}";do
      __fzf_obc_expand_tilde_by_ref pattern
      if [[ "${pattern}" =~ ^/ ]];then
        sep="' -o -path '"
      else
        sep="' -o -path '*/"
      fi
      pattern=${pattern%\/}
      str+=$(printf "%s" "${pattern/#/$sep}")
    done
    str+="' \) -prune -o"
  fi
  eval "${var}=\"${str}\""
}


# To use custom commands instead of find, override __fzf_obc_search later
# Return: list of files/directories separated by $'\0'
__fzf_obc_search() {
  local IFS=$'\n'
  local cur type xspec
  cur="${1}"
  type="${2}"
  xspec="${3}"

  local cur_clean
  cur_clean="${cur%%\**}"

  local cur_expanded
  cur_expanded=${cur_clean:-./}

  __fzf_obc_expand_tilde_by_ref cur_expanded

  local startdir
  if [[ "${cur_expanded}" != *"/" ]];then
    startdir="${cur_expanded}*"
    mindepth="0"
    maxdepth="0"
  else
    startdir="${cur_expanded}"
    mindepth="1"
    maxdepth="1"
  fi

  if [[ "${cur}" == *"**" ]];then
    maxdepth="${FZF_OBC_GLOBS_MAXDEPTH}"
    local exclude_string
    __fzf_obc_globs_exclude exclude_string
  fi

  local cmd
  cmd="command find ${startdir}"
  cmd+=" -mindepth ${mindepth} -maxdepth ${maxdepth} "
  cmd+=" ${exclude_string} "

  case ${type} in
    paths)
      cmd+=" \( -type d -printf '%p/\0' -or -printf '%p\0' \)"
      ;;
    files)
      cmd+=" \( -type f -printf '%p\0' -or -type l -printf '%p\0' \)"
      ;;
    dirs)
      cmd+=" -type d -printf '%p/\0' "
      ;;
  esac

  cmd+=" 2> /dev/null"

  if [[ "${cur_expanded}" != "${cur_clean}" ]];then
    cmd=" sed -z s'#${cur_expanded//\//\\/}#${cur_clean//\//\\/}#' < <(${cmd})"
  fi

  if [[ "${type}" == "files" ]] && [[ -n ${xspec} ]];then
    cmd=" __fzf_obc_search_filter_bash '${xspec}' < <(${cmd})"
  fi

  eval "${cmd}"
  return 0
}

__fzf_obc_search_filter_bash() (
  # Input: a list of strings separated by $'\0'
  # Params:
  #   $1: an optional glob patern for filtering
  # Return: a list of strings filtered and separate by $'\0'
  shopt -s extglob
  local xspec="$1"
  [[ -z "${xspec}" ]] && cat
  while IFS= read -t 0.1 -d $'\0' -r file;do
    [[ "${file}" == ${xspec} ]] && printf "%s\0" "${file}"
  done
)

__fzf_obc_expand_tilde_by_ref ()
{
  local expand
  # Copy from original bash complete
  if [[ ${!1} == \~* ]]; then
    read -r -d '' expand < <(printf ~%q "${!1#\~}")
    eval "$1"="${expand}";
  fi
}

__fzf_obc_tilde ()
{
  # Copy from original bash complete
  local result=0;
  if [[ $1 == \~* && $1 != */* ]]; then
      COMPREPLY=($( compgen -P '~' -u -- "${1#\~}" ));
      result=${#COMPREPLY[@]};
      [[ $result -gt 0 ]] && compopt -o filenames 2> /dev/null;
  fi;
  return "${result}"
}

__fzf_obc_cmd() {
    fzf --read0 --print0
}

__fzf_obc_read_compreply() {
  local IFS=$'\n'
  if [[ "${#COMPREPLY[@]}" -ne 0 ]];then
    if [[ "${cur}" == *"**" ]];then
      local item
      compopt +o filenames
      __fzf_compreply < <(
        printf "%s\0" "${COMPREPLY[@]}" \
        | __fzf_obc_sort_cmd \
        | FZF_DEFAULT_OPTS="--reverse --height ${FZF_OBC_HEIGHT} ${FZF_OBC_GLOBS_OPTS} ${FZF_OBC_GLOBS_BINDINGS}" \
          __fzf_obc_cmd \
        | while IFS= read -d $'\0' -r item;do printf "%q " "${item}" | sed 's/^\\~/~/';done \
        | sed 's/ $//'
      )
    else
      __fzf_compreply < <(
        printf "%s\0" "${COMPREPLY[@]}" \
        | __fzf_obc_sort_cmd \
        | FZF_DEFAULT_OPTS="--reverse --height ${FZF_OBC_HEIGHT} ${FZF_OBC_OPTS} ${FZF_OBC_BINDINGS}" \
          __fzf_obc_cmd \
        | sed 's#/\x0#\x0#'
      )
    fi
    printf '\e[5n'
  else
    if [[ "${cur}" == *"**" ]];then
      compopt -o nospace
      COMPREPLY=( "${cur%\*\*}" )
    fi
  fi
}

