name: On pull request

on:
  pull_request:
  push:
    branches-ignore:
      - 'master'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # Avoid noisy outputs like "tput: No value for $TERM and no -T specified"
  TERM: xterm-256color
  UBUNTU_IMAGE: &UBUNTU_IMAGE ubuntu-22.04
  CI: "True"

jobs:
  Tests:
    uses: ./.github/workflows/tests.yml
    with:
      runner-image: *UBUNTU_IMAGE
