name: Tests
on: [push, pull_request]
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
env:
  # Avoid noisy outputs like "tput: No value for $TERM and no -T specified"
  TERM: xterm-256color
jobs:
  Tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target:
          - .github/workflows/pull_request.yml
          - test-shellcheck
          - test-bats-bash-4.4.23-gnu-true
          - test-bats-bash-3.2.57-gnu-true
          - test-bats-bash-4.3.48-gnu-true
          - test-bats-bash-4.1.17-gnu-true
          - test-bats-bash-4.4.23-gnu-false
          - test-bats-bash-3.2.57-gnu-false
          - test-bats-bash-4.3.48-gnu-false
          - test-bats-bash-4.1.17-gnu-false
          - test-tmux-bash-4.4.23-gnu-true
          - test-tmux-bash-3.2.57-gnu-true
          - test-tmux-bash-4.3.48-gnu-true
          - test-tmux-bash-4.1.17-gnu-true
          - test-tmux-bash-4.4.23-gnu-false
          - test-tmux-bash-3.2.57-gnu-false
          - test-tmux-bash-4.3.48-gnu-false
          - test-tmux-bash-4.1.17-gnu-false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        if: contains(matrix.target, 'tmux')
        uses: actions/setup-python@v5.6.0
        with:
          python-version-file: 'test/tmux/.python-version'
      - name: Install Tmux
        if: contains(matrix.target, 'tmux')
        run: |
          sudo apt-get install tmux
      - name: make ${{matrix.target}}
        shell: 'script -qfec "bash {0}"'
        run: make ${{matrix.target}}
