on:
  workflow_call:
    inputs:
      runner-image:
        required: false
        type: string
        default: ubuntu-latest
    outputs:
      cache-path:
        value: ${{ jobs.pyenv.outputs.cache-path }}
      cache-key:
        value: ${{ jobs.pyenv.outputs.cache-key }}
      cache-restore-keys:
        value: ${{ jobs.pyenv.outputs.cache-restore-keys }}
env:
  TERM: xterm-256color
  CI: "True"
jobs:
  pyenv:
    uses: rockandska/ga-workflows/.github/workflows/pyenv-install.yml@master
    with:
      runner-image: ${{ inputs.runner-image }}
  Tests:
    needs: pyenv
    runs-on: ${{ inputs.runner-image }}
    strategy:
      matrix:
        target:
          - shellcheck
          - test-bats-3.2.57
          - test-bats-gnu-3.2.57
          - test-bats-4.1.17
          - test-bats-gnu-4.1.17
          - test-bats-4.3.48
          - test-bats-gnu-4.3.48
          - test-tmux-3.2.57
          - test-tmux-gnu-3.2.57
          - test-tmux-4.1.17
          - test-tmux-gnu-4.1.17
          - test-tmux-4.3.48
          - test-tmux-gnu-4.3.48
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Restore pyenv cache
        if: contains(matrix.target, 'tmux')
        id: pyenv-cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ needs.pyenv.outputs.cache-path }}
          key: ${{ needs.pyenv.outputs.cache-key }}
          restore-keys: ${{ needs.pyenv.outputs.cache-restore-keys }}
      - name: Setup PYENV
        if: contains(matrix.target, 'tmux')
        run: |
          echo "${{ needs.pyenv.outputs.cache-path }}/bin" >> "$GITHUB_PATH"
          echo "PYENV_ROOT=${{ needs.pyenv.outputs.cache-path }}" >> "$GITHUB_ENV"
      - name: Install Tmux
        if: contains(matrix.target, 'tmux')
        run: |
          sudo apt-get install tmux
      - name: make ${{matrix.target}}
        shell: 'script -qfec "bash {0}"'
        run: make ${{matrix.target}}
